[package]
name = "rendy-frame"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"

[dependencies]
derivative = "1.0"
either = "1.5"
gfx-hal = "0.1.0"
failure = "0.1"
log = "0.4"
relevant = "0.3"
smallvec = "0.6"
rendy-command = { path = "../command" }
rendy-factory = { path = "../factory" }
rendy-memory = { path = "../memory" }
rendy-resource = { path = "../resource" }
